spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev

server:
  port: 8080

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

app:
  ctx-timeout: 12
  ctx-timeout-unit: HOURS
  avatar-path: avatar/